blog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', PrimaryPageBlog.as_view(), name='blog_primary'),
    path('blog-page/<str:slug>/', PageBlog.as_view(), name='blog_page'),
    path('blog-page/likes_or_dislikes/<str:slug>', сhange_model_comment, name ='comment_likes_or_dislikes'),
   
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse


class Blog(models.Model):
    """ Модель Блога """
    title = models.CharField('Название', max_length=150, unique=True)
    slug = models.SlugField('URL', max_length=150, unique=True)
    created_at = models.DateField('Дата', auto_now_add=True)
    posted_by = models.BooleanField('Опубликовано', default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog_page', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ['-created_at', ]

comment/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from blog.models import Blog


class BlogComment(MPTTModel):
    """  Модель комментарий """
    name = models.ForeignKey(User, blank=True, null=True,
                             on_delete=models.CASCADE, verbose_name='Пользователь')
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True,
                            blank=True, related_name='children', verbose_name='Коментарий')
    blog = models.ForeignKey(
        Blog, on_delete=models.CASCADE, verbose_name='Блог', null=True, blank=True)
    comment_text = models.TextField('Текст коментария', max_length=500)
    like = models.IntegerField('Мне нравится', default=0)
    like_user = models.ManyToManyField(User, related_name='comment_blog_like_rn',
                                       verbose_name="Пользователи поставившие мне нравиться", blank=True)
    dislike = models.IntegerField('Мне не нравится', default=0)
    dislike_user = models.ManyToManyField(
        User, related_name='comment_blog_dislake_rn', verbose_name="Пользователи поставившие мне не нравиться", blank=True)
    publication_date = models.DateField('Дата публикации', auto_now_add=True)
    update_date = models.DateField('Дата обновления', auto_now=True)
    posted_by = models.BooleanField('Опубликовано', default=True)

    def __str__(self):
        return str(self.name) + ': ' + self.comment_text[:25] + '...'

    class MPTTMeta:
        order_insertion_by = ['-publication_date']

    class Meta:
        verbose_name = 'Коментария'
        verbose_name_plural = 'Коментарии'

comment/forms.py
from django import forms
from .models import BlogComment




class BlogCommentForm(forms.ModelForm):
    """Форма комментарий"""
    class Meta:
        model = BlogComment
        fields = ['comment_text', 'parent']
        widgets = {
            'comment_text': forms.TextInput(attrs={'class': 'form-control', 'rows': 1, 'placeholder': 'Ваш коментарий', 'id': False})
        }

blog/views.py
from django.shortcuts import redirect
from django.db.models import Count
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User

from comment.models import BlogComment
from comment.forms import BlogCommentForm
from .models import Blog


class PrimaryPageBlog(ListView):
    """ Blog list view """
    """ Представление списка блогов """
    model = Blog
    template_name = 'blog/primary.html'

    def get_context_data(self, **kwargs):
        """ Adding additional context to the blog view """
        """ Добавление дополнительного контекста к представлению списка блогов """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Блог'
        return context

    def get_queryset(self):
        return Blog.objects.filter(posted_by=True)


class PageBlog(FormMixin, DetailView):
    """ Blog Submission """
    """ Представление блога """
    model = Blog
    form_class = BlogCommentForm
    initial = {}
    template_name = 'blog/blog.html'
    context_object_name = 'object'

    def post(self, request, *args, **kwargs):
        """ Receiving data sent by POST request. Form data comment """
        """ Получение данных отправленных POST запросом. Данные формы комментарий """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        """ Checks the form, fills in the data, saves to the model """
        """ Проверяет форму, заполняет данные, сохраняет в модели """
        self.object = form.save(commit=False)
        self.object.blog = self.get_object()
        self.object.name = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        """ Redirects to the address on successful form validation. Comment forms """
        """ Перенаправляет по адресу, при успешном прохождении валидации формы. Формы комментарии """
        return reverse_lazy('blog_page', kwargs={'slug': self.kwargs['slug']})

    def get_context_data(self, **kwargs):
        """ Adding additional context to the blog view """
        """ Добавление дополнительного контекста к представлению блога """
        context = super().get_context_data(**kwargs)
        context['title'] = Blog.objects.get(slug=self.kwargs['slug'])
        context['comments'] = BlogComment.objects.annotate(
            cnt=Count('children')).filter(blog__slug=self.kwargs['slug'])
        return context


def сhange_model_comment(request, slug):
    """ Comments on articles, handling of links 'I like' and 'I don't like' """
    """ Комментарии к статьям, обработка ссылки 'мне нравиться' и 'мне не нравиться' """

    # 1.  Getting data from a post request, from hidden fields
    # 1. (Получение  данных из пост запроса, из скрытых полей)
    get_user = request.POST.get('get_user')
    get_obj_comment = request.POST.get('get_likes_or_dislikes')
    get_comment = BlogComment.objects.get(pk=request.POST.get('get_comment'))

    get_obj_user = User.objects.get(username=get_user)

    # 2.  Get a boolean value, about the content of the user among those who have checked 'I like' or 'I do not like'
    # 2. (Получение булевого значения, о содержании пользователя среди поставивших отметку 'мне нравиться' или 'мне не нравиться')
    exists_user_like = get_comment.like_user.filter(username=get_user).exists()
    exists_user_dislike = get_comment.dislike_user.filter(
        username=get_user).exists()

    # 3.  Checks button press I like
    # 3. (Проверяет нажатие кнопки мне нравиться)
    if get_obj_comment == 'likes':
        # 3.1  Checks user content among those who have checked I like
        # 3.1 (Проверяет содержание пользователя среди поставивших отметку мне нравиться)
        if exists_user_like:
            get_comment.like_user.remove(get_obj_user.pk)
            like = get_comment.like - 1
            get_comment.like = like
            get_comment.save()
        else:
            get_comment.like_user.add(get_obj_user)
            like = get_comment.like + 1
            get_comment.like = like
            get_comment.save()
            # 3.2  Before putting the mark 'I like', it checks the user's content among those who marked the mark I do not like, and removes it from this list
            # 3.2 (Перед проставлением отметки 'Мне нравиться', проверяет содержание пользователя среди поставивших отметку мне не нравиться, и удаляет из данного списка)
            if exists_user_dislike:
                get_comment.dislike_user.remove(get_obj_user.pk)
                dislike = get_comment.dislike - 1
                get_comment.dislike = dislike
                get_comment.save()
    # 4.  Checks button press I don't like
    # 4. (Проверяет нажатие кнопки мне не нравиться)
    elif get_obj_comment == 'dislikes':
        # 4.1  Checks the user's content among those who ticked I don't like
        # 4.1 (Проверяет содержание пользователя среди поставивших отметку мне не нравиться)
        if exists_user_dislike:
            get_comment.dislike_user.remove(get_obj_user.pk)
            dislike = get_comment.dislike - 1
            get_comment.dislike = dislike
            get_comment.save()
        else:
            get_comment.dislike_user.add(get_obj_user)
            dislike = get_comment.dislike + 1
            get_comment.dislike = dislike
            get_comment.save()
            # 4.2  Before checking the checkbox 'I do not like it', it checks the user's content among those who checked the checkbox I like, and removes it from this list
            # 4.2 (Перед проставлением отметки 'Мне не нравиться', проверяет содержание пользователя среди поставивших отметку мне нравиться, и удаляет из данного списка)
            if exists_user_like:
                get_comment.like_user.remove(get_obj_user.pk)
                like = get_comment.like - 1
                get_comment.like = like
                get_comment.save()
    return redirect('blog_page', slug=slug)

comment/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/include_html/comment.html
{% load verbose_names %} <!-- File: templatetags/verbose_names.py-->
<!--Simple tag для получения verbose_name-->
<!--Simple tag for getting verbose_name-->
{% load static %}

<div class="blog-detail-comments">
    <span class="font-weight-bold">Комментарии:</span> 
    <span class="text-monospace">({{object.blogcomment_set.count}})</span>

<!--Форма добавления комментарий-->
<!--Add comment form-->

        {% if user.is_authenticated %}
            <form class="mt-3" action="" method="POST">
                {% csrf_token %}
                    {{form.comment_text}}
                    {{form.error}}
                <div class="mt-2  text-right">
                    <button class="btn btn-dark" type="submit">Отправить</button>
                </div>
            </form>

        {% else %}
            <p class = ".text-danger">Пожалуйста, авторизуйтесь, чтобы оставлять комментарии</p>
        {% endif %}
    

<!-- Обход комментарий -->
<!-- Bypass comment -->

<div class="container-comments">
        {% load mptt_tags %}
        <ul>
            {% recursetree comments %}
                <li data-circle=true class= "{% if node.level == 0 %} JSCountComment {% endif %}">
                    <div class="row" style="font-weight: normal;">
                        <div class="col-md-6">
                            <span class="font-weight-bold text-dark">
                                {% get_verbose_field_name node "name" %}: 
                            </span>
                            <span class="text-monospace text-dark">{{ node.name }}</span><br>
                            <span class="text-monospace text-dark">{{node.publication_date}}</span><br>
                        </div>
                        <div class="col-md-6 text-right">
                            {% block container_blog_comment_likes_or_dislikes %}
                                {% include 'blog/include_html/comment_likes_or_dislikes.html'%}
                            {% endblock %}
                        </div>
                    </div>
                    <span class="text-monospace text-dark" style="font-weight: normal;">{{node.comment_text}}</span><br>

<!-- Определение уровни вложенности коментарий -->  
                    {% if user.is_authenticated and node.level < 2 %} <!--================================-->
<!-- Determining the nesting levels of comments -->
                    <span class="answer-auxiliary answer" data-box=true>Ответить
                        <div  class = 'jsClassChange display-none'>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="jsPlaceholder">
                                    {{ form.comment_text }}
                                    {{ form.error }}
                                    <input class='display-none' type="hidden" name="parent" value="{{ node.pk }}">
                                    <!--Определение предка комментария--> <!-- Definition of the parent of the comment -->
                                </div>
                                <div class="mt-2 text-right">
                                    <button class="btn btn-dark" type="submit">Отправить</button>
                                </div>
                            </form>
                        </div>
                    </span>
<!--Если уровни вложенности комментариев превышает указанного, тогда прекратить вложения комментарий.  
    Построить остальные ответные комментарии: "Имя пользователя комментария, комментария к пользователю"-->
                    {% else %}
<!--If the nesting levels of comments exceed the specified, then stop nesting the comment. 
    Build the rest of the response comments: "Username of comment, user comment"-->
                    <span class="jsAnswerUser answer-auxiliary answer" data-box=true>Ответить
                        <div  class = 'jsClassChange display-none'>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="jsPlaceholder">
                                    {{form.comment_text}}
                                    {{form.error}}
                                    <input class = "display-none" type="hidden" name="parent" value="{{ node.parent.pk }}">
                                    <!--Определение предка у предка комментария--> 
                                    <!--Determining the ancestor of the comment ancestor-->
                                    <input class = "jsNameUser display-none" type = "hidden" value = "{{node.name}}">
                                    <!--Определения имени пользователя у предка комментария, для построения ответа-->
                                    <!--Determining the username of the ancestor of the comment to build a response-->
                                </div>
                                <div class="mt-2 text-right">
                                    <button class="jsResponseToUser btn btn-dark" type="submit">Отправить</button>
                                </div>
                            </form>
                        </div>
                    </span>
                    {% endif %}
                    {% if not node.is_leaf_node %}
                    <span class="jsAnswers answer-auxiliary answer {%if user.is_authenticated%} blog-detail-comments-indentation {% endif %} text-decoration-none" data-square=true>Ответы ({{node.cnt}})
                        <ul class="children display-none">
                            {{ children }}
                        </ul>
                    </span>
                    {% endif %}
                </li>            
            {% endrecursetree %}
        </ul> 

        <div class = "container-more-comments">
            <a class="JSexpandСomment btn btn-dark" type="submit">Еще комментарии</a>
        </div>

        <script src = "{% static 'blog/script.js' %}"></script>
    </div>
</div>

blog/templates/blog/include_html/comment_likes_or_dislikes.html
{% if user.is_authenticated %}
    <form action="{% url 'comment_likes_or_dislikes' object.slug %}" method="POST">
        {% csrf_token %}
        <input class="display-none" name='get_user'  type="hidden" value={{user}}>
        <input class="display-none" name='get_comment'  type="hidden" value={{node.pk}}>
        <button class="comment_btn_likes_or_dislikes" name="get_likes_or_dislikes" value="likes"  type="submit">
            <svg class="comment-svg-likes" width="15" version="1.1" viewBox="0 0 128 128" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <g>
                    <path d="M117.5,68.2c3-2,5-5.4,5-9.2c0-6.1-4.9-11-11-11h-24c-1.7,0-3-1.3-3-3V18c0-8.8-7.2-16-16-16   c-2.8,0-5,2.2-5,5v18.7C59.7,37,52.7,46.9,43.3,54.3l-3.1,2.5v-2.7H5.5V126h34.7v-6c6.4,3.9,13.7,6,21.2,6h39.1c5.5,0,10-4.5,10-10   c0-2.3-0.8-4.5-2.1-6.1c5.7-0.9,10.1-5.9,10.1-11.9c0-3.5-1.5-6.6-3.8-8.8c4.6-1.7,7.8-6.1,7.8-11.2   C122.5,74,120.5,70.4,117.5,68.2z M36.2,122H9.5V58.1h26.7V122z M110.5,86c0,0-3.3,0-4,0v4c4.4,0,8,3.6,8,8s-3.6,8-8,8h-6v4   c3.3,0,6,2.7,6,6s-2.7,6-6,6H61.4c-7.6,0-15-2.4-21.2-6.8V61.9l5.6-4.4c10.1-8,17.5-18.6,21.6-30.8l0.1-0.3V7c0-0.6,0.4-1,1-1   c6.6,0,12,5.4,12,12v27c0,3.9,3.1,7,7,7h24c3.9,0,7,3.1,7,7s-3.1,7-7,7h-1v4c4.4,0,8,3.6,8,8S114.9,86,110.5,86z" fill="#3EBBC4"/>
                </g>
            </svg>
        </button>
        {{node.like}} 
        <button class="comment_btn_likes_or_dislikes" name="get_likes_or_dislikes" value="dislikes"  type="submit">
            <svg class="comment-svg-dislikes" width="15"   version="1.1" viewBox="0 0 128 128" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <g>
                    <path d="M117.5,68.2c3-2,5-5.4,5-9.2c0-6.1-4.9-11-11-11h-24c-1.7,0-3-1.3-3-3V18c0-8.8-7.2-16-16-16   c-2.8,0-5,2.2-5,5v18.7C59.7,37,52.7,46.9,43.3,54.3l-3.1,2.5v-2.7H5.5V126h34.7v-6c6.4,3.9,13.7,6,21.2,6h39.1c5.5,0,10-4.5,10-10   c0-2.3-0.8-4.5-2.1-6.1c5.7-0.9,10.1-5.9,10.1-11.9c0-3.5-1.5-6.6-3.8-8.8c4.6-1.7,7.8-6.1,7.8-11.2   C122.5,74,120.5,70.4,117.5,68.2z M36.2,122H9.5V58.1h26.7V122z M110.5,86c0,0-3.3,0-4,0v4c4.4,0,8,3.6,8,8s-3.6,8-8,8h-6v4   c3.3,0,6,2.7,6,6s-2.7,6-6,6H61.4c-7.6,0-15-2.4-21.2-6.8V61.9l5.6-4.4c10.1-8,17.5-18.6,21.6-30.8l0.1-0.3V7c0-0.6,0.4-1,1-1   c6.6,0,12,5.4,12,12v27c0,3.9,3.1,7,7,7h24c3.9,0,7,3.1,7,7s-3.1,7-7,7h-1v4c4.4,0,8,3.6,8,8S114.9,86,110.5,86z" fill="#3EBBC4"/>
                </g>
            </svg>
        </button>
        {{node.dislike}} 
    </form>
                           
{% else %}
    <svg class="comment-svg-likes" width="15" version="1.1" viewBox="0 0 128 128" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g>
            <path d="M117.5,68.2c3-2,5-5.4,5-9.2c0-6.1-4.9-11-11-11h-24c-1.7,0-3-1.3-3-3V18c0-8.8-7.2-16-16-16   c-2.8,0-5,2.2-5,5v18.7C59.7,37,52.7,46.9,43.3,54.3l-3.1,2.5v-2.7H5.5V126h34.7v-6c6.4,3.9,13.7,6,21.2,6h39.1c5.5,0,10-4.5,10-10   c0-2.3-0.8-4.5-2.1-6.1c5.7-0.9,10.1-5.9,10.1-11.9c0-3.5-1.5-6.6-3.8-8.8c4.6-1.7,7.8-6.1,7.8-11.2   C122.5,74,120.5,70.4,117.5,68.2z M36.2,122H9.5V58.1h26.7V122z M110.5,86c0,0-3.3,0-4,0v4c4.4,0,8,3.6,8,8s-3.6,8-8,8h-6v4   c3.3,0,6,2.7,6,6s-2.7,6-6,6H61.4c-7.6,0-15-2.4-21.2-6.8V61.9l5.6-4.4c10.1-8,17.5-18.6,21.6-30.8l0.1-0.3V7c0-0.6,0.4-1,1-1   c6.6,0,12,5.4,12,12v27c0,3.9,3.1,7,7,7h24c3.9,0,7,3.1,7,7s-3.1,7-7,7h-1v4c4.4,0,8,3.6,8,8S114.9,86,110.5,86z" fill="#3EBBC4"/>
        </g>
    </svg> {{node.like}} 
    <span class = "comment_likes_and_dislikes_margin"></span>
    <svg class="comment-svg-dislikes" width="15"   version="1.1" viewBox="0 0 128 128" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g>
            <path d="M117.5,68.2c3-2,5-5.4,5-9.2c0-6.1-4.9-11-11-11h-24c-1.7,0-3-1.3-3-3V18c0-8.8-7.2-16-16-16   c-2.8,0-5,2.2-5,5v18.7C59.7,37,52.7,46.9,43.3,54.3l-3.1,2.5v-2.7H5.5V126h34.7v-6c6.4,3.9,13.7,6,21.2,6h39.1c5.5,0,10-4.5,10-10   c0-2.3-0.8-4.5-2.1-6.1c5.7-0.9,10.1-5.9,10.1-11.9c0-3.5-1.5-6.6-3.8-8.8c4.6-1.7,7.8-6.1,7.8-11.2   C122.5,74,120.5,70.4,117.5,68.2z M36.2,122H9.5V58.1h26.7V122z M110.5,86c0,0-3.3,0-4,0v4c4.4,0,8,3.6,8,8s-3.6,8-8,8h-6v4   c3.3,0,6,2.7,6,6s-2.7,6-6,6H61.4c-7.6,0-15-2.4-21.2-6.8V61.9l5.6-4.4c10.1-8,17.5-18.6,21.6-30.8l0.1-0.3V7c0-0.6,0.4-1,1-1   c6.6,0,12,5.4,12,12v27c0,3.9,3.1,7,7,7h24c3.9,0,7,3.1,7,7s-3.1,7-7,7h-1v4c4.4,0,8,3.6,8,8S114.9,86,110.5,86z" fill="#3EBBC4"/>
        </g>
    </svg> {{node.dislike}}                            
{% endif %}